/**
 * Firestore collection names for the shared "aim119" project.
 * USERS / TRANSACTIONS are shared across every aim119 app (AP points economy).
 * ZENTARO_* collections are namespaced so this app never collides with other bots.
 */
export const COLLECTIONS = {
  USERS: 'users',
  TRANSACTIONS: 'transactions',
  ROULETTE_SPINS: 'roulette_spins',
  ZENTARO_WALLETS: 'zentaro_wallets',
  ZENTARO_PRODUCTS: 'zentaro_products',
  ZENTARO_ORDERS: 'zentaro_orders',
  ZENTARO_TICKETS: 'zentaro_tickets',
  ZENTARO_NFTS: 'zentaro_nfts',
  ZENTARO_CONTRIBUTIONS: 'zentaro_contributions',
  ZENTARO_POSTS: 'zentaro_posts',
  ZENTARO_VENDOR_INQUIRIES: 'zentaro_vendor_inquiries',
  ZENTARO_BOTTLE_CAP_CLAIMS: 'zentaro_bottle_cap_claims',
  ZENTARO_PRODUCT_REVIEWS: 'zentaro_product_reviews',
  ZENTARO_ZTRO_REWARD_CODES: 'zentaro_ztro_reward_codes',
  ZENTARO_DEPOSITS: 'zentaro_deposits',
  ZENTARO_BARRELS: 'zentaro_barrels',
  ZENTARO_BARREL_PRICING_CONFIG: 'zentaro_barrel_pricing_config',
  ZENTARO_ZTARO_PRICE_SNAPSHOTS: 'zentaro_ztaro_price_snapshots',
  ZENTARO_ZTARO_PRICING_CONFIG: 'zentaro_ztaro_pricing_config',
  ZENTARO_DAO_STAKE_BONUS_CLAIMS: 'zentaro_dao_stake_bonus_claims',
  ZENTARO_DAO_PROPOSAL_NOTES: 'zentaro_dao_proposal_notes',
  ZENTARO_INVESTOR_WATCHLIST: 'zentaro_investor_watchlist',
  ZENTARO_DRINKS_PRODUCTS: 'zentaro_drinks_products',
  ZENTARO_DRINKS_PRODUCERS: 'zentaro_drinks_producers',
  ZENTARO_DRINKS_INGREDIENTS: 'zentaro_drinks_ingredients',
  ZENTARO_DRINKS_COCKTAILS: 'zentaro_drinks_cocktails',
  ZENTARO_DRINKS_USER_RATINGS: 'zentaro_drinks_user_ratings',
  ZENTARO_DRINKS_SOURCES: 'zentaro_drinks_sources',
  ZENTARO_DRINKS_SYNC_LOGS: 'zentaro_drinks_sync_logs',
  ZENTARO_DRINKS_RANKING_CONFIG: 'zentaro_drinks_ranking_config',
  ZENTARO_DRINKS_FOOD_PAIRINGS: 'zentaro_drinks_food_pairings',
  ZENTARO_WHISKY_DISTILLERIES: 'zentaro_whisky_distilleries',
  ZENTARO_WHISKY_AUCTION_HOUSES: 'zentaro_whisky_auction_houses',
  ZENTARO_WHISKY_MARKET_META: 'zentaro_whisky_market_meta',
  ZENTARO_WHISKY_WATCHLIST: 'zentaro_whisky_watchlist',
  ZENTARO_WHISKY_TARGETS: 'zentaro_whisky_targets',
} as const;
